### ISSUE TITLE
Incorrect English construction

### ISSUE THREAD

**Issue by donaldcallen** [Sobeston/ziglearn#123]
In the section on Runtime Safety, the last sentence of the first paragraph begins "Users are strongly recommended to develop and test ....". This is not grammatically correct. Suggested fix: "It is strongly recommended that users develop and test ...."

**Comment by Cons-Cat** [comment]
[Elements of Style](https://faculty.washington.edu/heagerty/Courses/b572/public/StrunkWhite.pdf)

This is the book that taught me English. On page 11, you may read about the rules of English active and passive voice. tl;dr the current phrasing of that sentence is reasonable. Subjectively, I disagree with your edit. The subject of your sentence has changed from "users" (who this manual generally directs) into a more ambiguous "it". This makes the subject the act of "develop and test"ing, which I personally find awkward.

If an active voice is strongly preferred here, making the subject a royal we as "We strongly recommend ..." may be better, but that  would require a refactor of all directives in the document for consistency. I personally feel that making users consistently the subject of sentences in this document is preferable to "we" or "it", because the function of this document is to direct users. The Rust Book often directs "you" to do something, or uses the term "Rustaceans" in a similar manner to "Users" in the Zig documents.

**Comment by ominitay** [comment]
> I personally feel that making users consistently the subject of sentences in this document is preferable to "we" or "it"...

There are several examples of the use of "we" in the website, for example: `Here, we allocate 100 bytes as a []u8.`. Either way, a consistent style should ideally be stuck to.
