### ISSUE TITLE
Issue with code highlighting of numbers with underscores.

### ISSUE THREAD

**Issue by GoodClover** [Sobeston/ziglearn#43]
If you look at [chapter-1 #integer-rules](https://ziglearn.org/chapter-1/#integer-rules) or [#floats](https://ziglearn.org/chapter-1/#floats)
The part explaining you you can use underscores has an example:
![image](https://user-images.githubusercontent.com/27222523/93002629-413d6780-f530-11ea-87cb-ebc98e192bf9.png)
In which the colouring of the numbers stops as soon as an underscore is hit.

I assume this is an easy fix, but I have no idea how this site generates it's code highlighting.

**Comment by GoodClover** [comment]
Just looked at the repo, it's just the markdown files?

Where exactly is the site stored or is it all auto-generated?
If it is how/what is used to generate should be mentioned in the README.

**Comment by Sobeston** [comment]
The site itself uses a build of https://github.com/gohugoio/hugo, which uses https://github.com/alecthomas/chroma for highlighting. The zig support was added in https://github.com/alecthomas/chroma/pull/364, and has this bug.

I don't plan on adding info on how it's generated, because it shouldn't need anything special to be generated - plain markdown is wanted.
