### ISSUE TITLE
White background theme

### ISSUE THREAD

**Issue by rofrol** [Sobeston/ziglearn#97]
Add switch for light/dark theme.

Also use this https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by rofrol** [comment]
I see that this site uses [Hugo]
(https://github.com/Sobeston/ziglearn/issues/43#issuecomment-691630749) but in the repo the is no tooling to generate html.

- theme used https://themes.gohugo.io/hugo-book/ [source](https://www.reddit.com/r/Zig/comments/hc01yk/i_made_a_website_in_an_attempt_to_make_it_easier/fvbzux2/?utm_source=reddit&utm_medium=web2x&context=3)
- Maybe add tooling and theme switcher like here https://github.com/nektro/ziglaunch

**Comment by jvo203** [comment]
Yes, a white theme would be most welcome. I exclusively use e-ink monitors which **REQUIRE** a black text on a white background. Black themes are unreadable on e-ink monitors due to the inherent limitations of the e-ink technology. As it stands, the ziglearn website is unusable on e-ink computer displays. It's a shame because it seems like a great resource to learn zig.

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/pull/197
